In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv(
    "new_results/cpmp/qm9/d_model_64_N_6_h_64_N_dense_6_lambda_attention_0.1_lambda_distance_0.6_leaky_relu_slope_0.16_dense_output_nonlinearity_tanh_distance_matrix_kernel_exp_dropout_0.1_aggregation_type_dummy_node/version_0/logs/csv/metrics.csv"
)
final_cols = [
    "valid best MAE",
    "valid best Pearson r",
    "valid best RMSE",
    "valid best R²",
    "valid final loss",
]

train_df = df[df["train loss"].notna()].dropna(axis=1)
eval_df = df[df["valid MAE"].notna()].dropna(axis=1)
final_matrix_df = (
    df[df[final_cols].notna().any(axis=1)].dropna(axis=1, how="all").max().to_frame().T
)

In [3]:
train_df

    step  train loss
0      0    1.082460
2      1    0.406646
4      2    0.388547
6      3    0.376803
8      4    0.362527
10     5    0.351782
12     6    0.346246
14     7    0.340663
16     8    0.336703
18     9    0.333099
20    10    0.331386
22    11    0.330062
24    12    0.328090
26    13    0.326427
28    14    0.324453
30    15    0.322652
32    16    0.320998
34    17    0.319746
36    18    0.318459
38    19    0.316372
40    20    0.314290
42    21    0.313143
44    22    0.311211
46    23    0.309660
48    24    0.308909

In [4]:
eval_df

    step  valid MAE  valid Pearson r  valid RMSE  valid R²
1      0   0.559719         0.185969    0.724880 -0.459108
3      1   0.492171         0.237593    0.656804 -0.197915
5      2   0.483932         0.255228    0.646413 -0.160313
7      3   0.468282         0.258474    0.626997 -0.091658
9      4   0.461477         0.262421    0.612972 -0.043365
11     5   0.462913         0.272026    0.609117 -0.030282
13     6   0.447697         0.282389    0.592335  0.025705
15     7   0.451549         0.290982    0.594371  0.018999
17     8   0.457490         0.298928    0.599818  0.000935
19     9   0.454694         0.304289    0.596378  0.012360
21    10   0.454666         0.310363    0.595823  0.014197
23    11   0.448204         0.314054    0.588636  0.037838
25    12   0.445535         0.319525    0.586256  0.045602
27    13   0.453522         0.325058    0.592885  0.023897
29    14   0.444797         0.333265    0.585125  0.049279
31    15   0.435374         0.339331    0.574744  0.082716
33    16   0.439184         0.345747    0.577640  0.073447
35    17   0.451490         0.354272    0.589066  0.036432
37    18   0.439210         0.361437    0.576855  0.075964
39    19   0.435076         0.370029    0.572401  0.090178
41    20   0.433992         0.376619    0.570629  0.095803
43    21   0.444781         0.382463    0.580890  0.062993
45    22   0.431564         0.383892    0.568514  0.102494
47    23   0.429642         0.384739    0.566874  0.107665
49    24   0.431146         0.385609    0.568392  0.102879

In [5]:
final_matrix_df

,step,valid best MAE,valid best Pearson r,valid best RMSE,valid best R²,valid final loss
0,0.0,0.429642,0.385609,0.566874,0.107665,0.431146